# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-14 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import domain.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_domain', domain.models.VarCharField(max_length=1000000000)),
                ('status', models.BooleanField(default=False)),
                ('description_domain', domain.models.VarCharField(max_length=1000000000)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Domain',
            },
        ),
    ]
